/**
 * EmployeeLeaveManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaveTypes } from './leaveTypes';


export interface LeaveTypesDto { 
    id?: string;
    name?: LeaveTypes;
    maxDaysAllowed?: number;
}
export namespace LeaveTypesDto {
}


