/**
 * EmployeeLeaveManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaveRequests } from './leaveRequests';


export interface LeaveRequestsDto { 
    id?: string;
    employeeId?: string;
    leaveTypeId?: string;
    fromTo?: string;
    toDate?: string;
    status?: LeaveRequests;
}
export namespace LeaveRequestsDto {
}


