/**
 * EmployeeLeaveManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LeaveTypes = {
    NUMBER_0: 0,
    NUMBER_2: 2
} as const;
export type LeaveTypes = typeof LeaveTypes[keyof typeof LeaveTypes];

