export * from './account.service';
import { AccountService } from './account.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './employeeSelfService.service';
import { EmployeeSelfServiceService } from './employeeSelfService.service';
export * from './employeeServices.service';
import { EmployeeServicesService } from './employeeServices.service';
export * from './founderService.service';
import { FounderServiceService } from './founderService.service';
export * from './leaveRequestsService.service';
import { LeaveRequestsServiceService } from './leaveRequestsService.service';
export * from './leaveTypesServices.service';
import { LeaveTypesServicesService } from './leaveTypesServices.service';
export * from './managerService.service';
import { ManagerServiceService } from './managerService.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './tokenAuth.service';
import { TokenAuthService } from './tokenAuth.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AccountService, ConfigurationService, EmployeeSelfServiceService, EmployeeServicesService, FounderServiceService, LeaveRequestsServiceService, LeaveTypesServicesService, ManagerServiceService, RoleService, SessionService, TenantService, TokenAuthService, UserService];
